[files]
extend-exclude = ["*.json", "*.js", "*.ipynb", "LICENSE", "*.css"]

[default.extend-identifiers]
HashiCorp = "HashiCorp"
aks = "aks"
AKS = "AKS"

[default.extend-words]
aks = "aks"
hashi = "hashi"
Hashi = "Hashi"
AKS = "AKS"
prev = "prev"
goes = "goes"
"ret" = "ret"
"flavor" = "flavor"
"artifact" = "artifact"
"artifacts" = "artifacts"
"ve" = "ve"
"initialize" = "initialize"
"initialized" = "initialized"
"eq" = "eq"
"Utilization" = "Utilization"
"parametrize" = "parametrize"
"seed" = "seed"
"center" = "center"
"authorization" = "authorization"
"capitalize" = "capitalize"
"te" = "te"

[default]
locale = "en-gb"
