site_name: "Open source MLOps on Azure in one step"
site_description: provision your MLOps stack to Azure in one step

repo_name: fuzzylabs/matcha-ml
repo_url: https://github.com/fuzzylabs/matcha

nav:
  - Introduction: 'index.md'
  - Getting started:
    - Deploying your first model: 'getting-started.md'
  - Concepts:
    - Workflows: 'workflows.md'
    - Azure Permissions: 'azure-permissions.md'
    - Azure Costs: 'costings.md'
  - Inside Matcha:
    - How does Matcha work: 'inside-matcha.md'
    - Resource stacks: 'resource-stacks.md'
    - Why we collect usage data: 'privacy.md'
  - Tools:
    - Data Version Control: 'data-version-control.md'
  - API Reference: 'references.md'


theme:
  name: material
  features:
    - content.code.copy
    - navigation.top
  logo: img/logo-white.png
  favicon: img/favicon.png


markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - md_in_html

plugins:
  - glightbox:
      zoomable: true
  - mkdocstrings:
      handlers:
        python:
          options:
            show_submodules: true
            separate_signature: true

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/fuzzy-labs/
      name: Fuzzy Labs on LinkedIn
    - icon: fontawesome/brands/twitter
      link: https://www.twitter.com/fuzzylabsai/
      name: Fuzzy Labs on Twitter

extra_css:
  - css/extra.css

copyright: Copyright &copy; <a href="https://fuzzylabs.ai">Fuzzy Labs Ltd</a>
