[tool.poetry]
name = "matcha-ml"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
license = "Apache-2.0 license"
readme = "README.md"
packages = [{include = "matcha_ml"}]

[tool.poetry.dependencies]
python = "^3.8"


[tool.poetry.group.doc.dependencies]
sphinx = "^6.1.3"
sphinx-autobuild = "^2021.3.14"
myst-parser = "^1.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
