apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "zenml.fullname" . }}
  labels:
    {{- include "zenml.labels" . | nindent 4 }}
data:
  ZENML_DEFAULT_USER_PASSWORD: {{ .Values.zenml.defaultPassword | b64enc | quote }}
  {{- if .Values.zenml.jwtSecretKey }}
  ZENML_JWT_SECRET_KEY: {{ .Values.zenml.jwtSecretKey | b64enc | quote }}
  {{- else if .Release.IsInstall }}
  ZENML_JWT_SECRET_KEY: {{ randAlphaNum 32 | b64enc | quote }}
  {{- else }}
  ZENML_JWT_SECRET_KEY: {{ (lookup "v1" "Secret" .Release.Namespace (include "zenml.fullname" .)).data.ZENML_JWT_SECRET_KEY | default (randAlphaNum 32 | b64enc | quote) }}
  {{- end }}
  {{- if .Values.zenml.database.url }}
  ZENML_STORE_URL: {{ .Values.zenml.database.url | b64enc | quote }}
  {{- if .Values.zenml.database.sslCa }}
  ZENML_STORE_SSL_CA: {{ .Files.Get .Values.zenml.database.sslCa | b64enc }}
  {{- end }}
  {{- if .Values.zenml.database.sslCert }}
  ZENML_STORE_SSL_CERT: {{ .Files.Get .Values.zenml.database.sslCert | b64enc }}
  {{- end }}
  {{- if .Values.zenml.database.sslKey }}
  ZENML_STORE_SSL_KEY: {{ .Files.Get .Values.zenml.database.sslKey | b64enc }}
  {{- end }}
  {{- end }}
  {{- if .Values.zenml.secretsStore.enabled }}
  {{- if eq .Values.zenml.secretsStore.type "sql" }}
  {{- if .Values.zenml.secretsStore.sql.encryptionKey }}
  ZENML_SECRETS_STORE_ENCRYPTION_KEY: {{ .Values.zenml.secretsStore.sql.encryptionKey | b64enc | quote }}
  {{- else if .Values.zenml.secretsStore.encryptionKey }}
  ZENML_SECRETS_STORE_ENCRYPTION_KEY: {{ .Values.zenml.secretsStore.encryptionKey | b64enc | quote }}
  {{- end }}
  {{- else if eq .Values.zenml.secretsStore.type "aws" }}
  {{- if .Values.zenml.secretsStore.aws.aws_access_key_id }}
  ZENML_SECRETS_STORE_AWS_ACCESS_KEY_ID: {{ .Values.zenml.secretsStore.aws.aws_access_key_id | b64enc | quote }}
  {{- end }}
  {{- if .Values.zenml.secretsStore.aws.aws_secret_access_key }}
  ZENML_SECRETS_STORE_AWS_SECRET_ACCESS_KEY: {{ .Values.zenml.secretsStore.aws.aws_secret_access_key | b64enc | quote }}
  {{- end }}
  {{- if .Values.zenml.secretsStore.aws.aws_session_token }}
  ZENML_SECRETS_STORE_AWS_SESSION_TOKEN: {{ .Values.zenml.secretsStore.aws.aws_session_token | b64enc | quote }}
  {{- end }}
  {{- else if eq .Values.zenml.secretsStore.type "azure" }}
  {{- if .Values.zenml.secretsStore.azure.azure_client_id }}
  ZENML_SECRETS_STORE_AZURE_CLIENT_ID: {{ .Values.zenml.secretsStore.azure.azure_client_id | b64enc | quote }}
  {{- end }}
  {{- if .Values.zenml.secretsStore.azure.azure_client_secret }}
  ZENML_SECRETS_STORE_AZURE_CLIENT_SECRET: {{ .Values.zenml.secretsStore.azure.azure_client_secret | b64enc | quote }}
  {{- end }}
  {{- if .Values.zenml.secretsStore.azure.azure_tenant_id }}
  ZENML_SECRETS_STORE_AZURE_TENANT_ID: {{ .Values.zenml.secretsStore.azure.azure_tenant_id | b64enc | quote }}
  {{- end }}
  {{- else if eq .Values.zenml.secretsStore.type "gcp" }}
  {{- if .Values.zenml.secretsStore.gcp.google_application_credentials }}
  GOOGLE_APPLICATION_CREDENTIALS_FILE: {{ .Files.Get .Values.zenml.secretsStore.gcp.google_application_credentials | b64enc | quote }}
  {{- end }}
  {{- else if eq .Values.zenml.secretsStore.type "hashicorp" }}
  {{- if .Values.zenml.secretsStore.hashicorp.vault_token }}
  ZENML_SECRETS_STORE_VAULT_TOKEN: {{ .Values.zenml.secretsStore.hashicorp.vault_token | b64enc | quote }}
  {{- end }}
  {{- end }}
  {{- end }}
  {{- if .Values.zenml.environment }}
  {{- range $key, $value := .Values.zenml.environment }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
  {{- end }}
