# templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-server
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-server
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-server
    spec:
      containers:
        - name: {{ .Release.Name }}-server
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 8000
          resources:
{{ toYaml .Values.resources | indent 12 }}
          volumeMounts:
            - mountPath: /index_data
              name: {{ .Release.Name }}-server-index
      restartPolicy: Always
      volumes:
        - name: {{ .Release.Name }}-server-index
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-server-index
